let quotes = [
    'As student leaders, our unity creates infinite possibilities.',
    'Dream big, act bigger – we’re the architects of our future.',
    'In every challenge lies the opportunity for greatness.',
    'Dare to be different, and you’ll make a difference.',
    'Together, we can turn visions into victories.',
    'Strive for progress, not perfection – that’s the key to success.',
    'Let passion be the fuel that drives our aspirations.',
    'Empowered minds empower the world.',
    'Unity is our strength, and determination is our weapon.',
    'Chase your dreams relentlessly, and they will chase you back.',
    'Believe in yourself, for you possess boundless potential.',
    'Dare to lead with kindness, and watch your impact multiply.',
    'Success is the sum of small efforts, repeated day in and day out.',
    'Our journey begins with a single step; let’s take it together.',
    'Be the change you wish to see, and inspire others to do the same.',
    'Embrace challenges as stepping stones to growth and wisdom.',
    'Innovation lies at the intersection of creativity and perseverance.',
    'Lead with empathy, and you’ll find understanding and harmony.',
    'Together, we’re not just a team – we’re a force of nature.',
    'Our voices united can spark a revolution of positive change.',
    'Failure is merely a stepping stone to future triumphs.',
    'Our potential is limitless, and so are the possibilities.',
    'In the face of adversity, we find our greatest strengths.',
    'Kindness is a language everyone understands – let’s speak it fluently.',
    'The power of a united student body knows no bounds.',
    'Success is a journey – enjoy every step of the way.',
    'Courage is not the absence of fear but the triumph over it.',
    'Every decision we make shapes our future – choose wisely.',
    'Aspire to inspire before we expire – make every moment count.',
    'Together, we can turn challenges into stepping stones.',
    'Embrace differences; they are the threads of our beautiful tapestry.',
    'Leadership is not about titles; it’s about empowering others.',
    'Persistence turns obstacles into opportunities.',
    'Let’s paint the canvas of our school with colors of unity and inclusion.',
    'Dare to disrupt the status quo and lead with innovation.',
    'A positive attitude can turn ordinary days into extraordinary memories.',
    'Together, we create ripples of change that can turn into waves.',
    'Believe in the power of teamwork, and we’ll conquer any challenge.',
    'Lead with integrity, and you’ll inspire trust in every heart.',
    'Our collective potential is like a fire waiting to ignite – let’s set it ablaze.',
    'Success is the sum of small efforts, repeated day in and day out.',
    'In unity, we find the strength to break down any barriers.',
    'Compassion is the thread that weaves us together as a family.',
    'Leadership is not about being in front; it’s about empowering those behind.',
    'Let’s turn challenges into opportunities and obstacles into stepping stones.',
    'Education is the foundation on which we build our dreams.',
    'Through collaboration, we magnify our impact on the world.',
    'Dream big, and then dream even bigger – the sky’s the limit.',
    'Success is not defined by what we achieve, but who we become.',
    'With courage and determination, we’ll rise above any adversity.',
    'In every setback, there’s a hidden setup for a remarkable comeback.',
    'Together, we can turn our vision into reality.',
    'In the tapestry of life, every thread has its purpose – embrace yours.',
    'Leadership is not about authority; it’s about empowering others.',
    'Dare to be different; it’s the first step towards making a difference.',
    'A positive attitude is a magnet for positive outcomes.',
    'With every step, we draw closer to the stars we wish upon.',
    'Kindness is the key that unlocks doors and hearts alike.',
    'In unity, we find the strength to overcome any challenge.',
    'Believe in yourself, and others will believe in you too.',
    'Our journey begins with a single step; let’s take it together.',
    'With determination and perseverance, we’ll reach new heights.',
    'Lead with empathy, and the world will follow.',
    'The journey of a thousand miles starts with a single step.',
    'Believe in your potential, and the world will believe in you.',
    'Through collaboration, we magnify our impact on the world.',
    'A united student body can overcome any obstacle.',
    'In every challenge lies an opportunity for growth.',
    'Kindness is the universal language of compassion.',
    'Together, we are architects of a brighter future.',
    'Embrace your uniqueness, for it adds color to our community.',
    'Success is not a destination; it’s a continuous journey.',
    'With determination and perseverance, we’ll reach new heights.',
    'In every obstacle lies a chance for innovation.',
    'Lead with integrity, and others will follow your lead.',
    'Our actions today shape the world of tomorrow.',
    'Embrace change, for it opens doors to new possibilities.',
    'Through unity, we discover our true strength.',
    'In the book of life, every chapter is a new opportunity.',
    'With positivity as our weapon, we can conquer any challenge.',
    'Empowerment is the key to unlocking our full potential.',
    'Together, we can turn dreams into reality.',
    'Dare to dream big, and the world will conspire to help you achieve it.',
    'In every moment, there is a chance for greatness.',
    'Leadership is not about popularity; it’s about service to others.',
    'With resilience and determination, we’ll make our mark on the world.',
    'Together, we can build bridges of understanding and compassion.',
    'In the eyes of unity, there are no differences, only strengths.',
    'Believe in yourself, and you’ll inspire others to do the same.',
    'The power to create change lies within each and every one of us.',
    'In unity, we discover the power to create lasting change.',
    'With courage and determination, we can move mountains.',
    'Success is not about winning; it’s about learning and growing.',
    'Lead with purpose, and you’ll leave a legacy of inspiration.',
    'In every setback, there is an opportunity for a comeback.',
    'Together, we can rewrite the story of our school’s future.',
    'Kindness is the foundation on which we build our community.',
    'Believe in yourself, and others will believe in you too.',
    'In every challenge, there lies an opportunity for greatness.',
    'Lead with empathy, and watch understanding flourish.',
    'Our strength lies in our unity, and our power is in our purpose.'
]